version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  publisher:
    build:
      context: ./Go-AMQP
      dockerfile: Dockerfile
    image: go-amqp
    entrypoint: /go-amqp server
    container_name: http_server_plus_amqp_bublisher
    volumes:
    - ./Volume:/application/log-files
    environment:
    - API_ENDPOINT=0.0.0.0:8000
    - BASE_PATH=/application/log-files
    - AMQP_URL=amqp://rabbitmq:5672
    - AMQP_EXCHANGE_NAME=exchange_upload_success
    - AMQP_EXCHANGE_KIND=fanout
    - AMQP_QUEUE_NAME=queue_upload_success
    - AMQP_ROUTING_KEY=upload_success
    ports:
    - '8000:8000'
    healthcheck:
      test: curl http://$API_ENDPOINT/health
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    image: go-amqp
    entrypoint: /go-amqp consumer
    container_name: amqp_consumer
    volumes:
    - ./Volume:/application/log-files
    environment:
    - BASE_PATH=/application/log-files
    - AMQP_URL=amqp://rabbitmq:5672
    - AMQP_EXCHANGE_NAME=exchange_upload_success
    - AMQP_EXCHANGE_KIND=fanout
    - AMQP_QUEUE_NAME=queue_upload_success
    - AMQP_ROUTING_KEY=upload_success
    depends_on:
      rabbitmq:
        condition: service_healthy
      publisher:
        condition: service_healthy
