---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: golang-amqp-integration-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: golang-amqp-integration-pvc
    namespace: golang-amqp
  storageClassName: ""
  nfs:
    server: 192.168.1.171
    path: /mnt/kubernetes-nfs/golang-amqp-integration
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golang-amqp-integration-pvc
  namespace: golang-amqp
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi