apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "GolangAMQP.producer.deploymentName" .}}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.producer.deployment.replicaCount }}
  template:
    metadata:
      labels:
{{ include "GolangAMQP.producer.podLabels" . | indent 8}}
    spec:
      initContainers:
      - name: producer-init-container
        image: {{ .Values.producer.deployment.initContainer.image }}
        command: ['sh', '-c', "until nc -zv {{ include "GolangAMQP.RabbitMQ.serviceName" . }}.{{ .Release.Namespace}}.svc.cluster.local {{ .Values.rabbitMQ.service.serverPort }}; do echo Waiting for RabbitMQ; sleep 2; done"]
      containers:
      - name: producer-container
        image: {{ .Values.producer.deployment.image }}
        args:
        - "server"
{{ include "GolangAMQP.producer.env" . | indent 8}}
        imagePullPolicy: {{ .Values.producer.deployment.imagePullPolicy }}
        livenessProbe:
{{ include "GolangAMQP.producer.healthCheck" . | indent 10}}
        readinessProbe:
{{ include "GolangAMQP.producer.healthCheck" . | indent 10}}
        volumeMounts:
        - name: {{ include "GolangAMQP.producer.deploymentName" .}}-volume-01
          mountPath: {{ .Values.producer.deployment.env.BASE_PATH }}
      volumes:
      - name: {{ include "GolangAMQP.producer.deploymentName" .}}-volume-01
        persistentVolumeClaim:
          claimName: {{ include "GolangAMQP.persistentVolumes.pvcName" .}}
  selector:
    matchLabels:
{{ include "GolangAMQP.producer.podLabels" . | indent 6 }}
