apiVersion: v1
kind: Service
metadata:
  name: {{ include "GolangAMQP.RabbitMQ.serviceName" .}}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.rabbitMQ.service.type }}
  selector:
{{include "GolangAMQP.RabbitMQ.podLabels" . | indent 4}}
  ports:
  - name: rabbitmq-server
    port: {{ .Values.rabbitMQ.service.serverPort }}
    targetPort: {{ .Values.rabbitMQ.service.serverPort }}
  - name: rabbitmq-http-server
    port: {{ .Values.rabbitMQ.service.httpPort }}
    targetPort: {{ .Values.rabbitMQ.service.httpPort }}